### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mschauer** [mschauer/Ciesielski.jl#1]
- [x] Implement Faber Schauder basis
- [x] Implement sampling Brownian bridge using Ciesieski's construction (based on Faber Schauder basis)
- [x] Implement Girsanov likelihood or use https://github.com/mschauer/Bridge.jl
- [x] Combine everything with MH with random walk update using persistence parameter rho

**Comment by mschauer** [comment]
Ping

**Comment by SebaGraz** [comment]
I wrote a simple function that updates the path with acceptance rate based on the girsanov function of the unconditioned measures since the conditioned measures are just proportional to the unconditioned measures.  The path is updated using the persistence parameter rho. The simple example is with the Ornstein Uhlenbeck process.

**Comment by mschauer** [comment]
Wow, now you can even go into the direction of parameter estimation of the mean reversion parameter of a discretely observed OU process with a Gibbs sampler noting that the parameter posterior is conjugate Gaussian given the continuous path.

**Comment by SebaGraz** [comment]
For the estimation of the mean reversion parameter  I thought I should follow this step:

- [x] generalize the Brownian Bridge for any initial and final point
- [x]  create new Type GBBcies <: Bridge.ContinuousTimeProcess{Float64} and extend Bridge.sample for GBBcies
- [x] sample from OU and retain the initial, middle and final point (3 initial observations)
- [x]  Implement Gibb Sampling as follow
Iterate N times:
1. for each segment do
	1.1. update path: propose Znew and accept through unconditioned Girsanov 
2. update variable \mu from the full conditional posterior and accept it. Save the value
return all the history of the parameter \mu

**Comment by mschauer** [comment]
Sounds like a plan!

**Comment by mschauer** [comment]
Can you push your changes to Github?

**Comment by SebaGraz** [comment]
For the posterior derivation I attached the pdf with the full derivation
[Posterior_conjugate.pdf](https://github.com/mschauer/Ciesielski.jl/files/2541375/Posterior_conjugate.pdf)

- [x]  Fix the Brownian Bridge sampler for any t0,t1, u,v.
